// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testing

import (
	"github.com/pbloigu/gonfig/api"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCached creates a new instance of MockCached. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCached(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCached {
	mock := &MockCached{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCached is an autogenerated mock type for the Cached type
type MockCached struct {
	mock.Mock
}

type MockCached_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCached) EXPECT() *MockCached_Expecter {
	return &MockCached_Expecter{mock: &_m.Mock}
}

// ListApplicationIds provides a mock function for the type MockCached
func (_mock *MockCached) ListApplicationIds() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListApplicationIds")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockCached_ListApplicationIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApplicationIds'
type MockCached_ListApplicationIds_Call struct {
	*mock.Call
}

// ListApplicationIds is a helper method to define mock.On call
func (_e *MockCached_Expecter) ListApplicationIds() *MockCached_ListApplicationIds_Call {
	return &MockCached_ListApplicationIds_Call{Call: _e.mock.On("ListApplicationIds")}
}

func (_c *MockCached_ListApplicationIds_Call) Run(run func()) *MockCached_ListApplicationIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCached_ListApplicationIds_Call) Return(strings []string) *MockCached_ListApplicationIds_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockCached_ListApplicationIds_Call) RunAndReturn(run func() []string) *MockCached_ListApplicationIds_Call {
	_c.Call.Return(run)
	return _c
}

// ListStatusChangeActions provides a mock function for the type MockCached
func (_mock *MockCached) ListStatusChangeActions(appId string) []api.Action {
	ret := _mock.Called(appId)

	if len(ret) == 0 {
		panic("no return value specified for ListStatusChangeActions")
	}

	var r0 []api.Action
	if returnFunc, ok := ret.Get(0).(func(string) []api.Action); ok {
		r0 = returnFunc(appId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.Action)
		}
	}
	return r0
}

// MockCached_ListStatusChangeActions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStatusChangeActions'
type MockCached_ListStatusChangeActions_Call struct {
	*mock.Call
}

// ListStatusChangeActions is a helper method to define mock.On call
//   - appId string
func (_e *MockCached_Expecter) ListStatusChangeActions(appId interface{}) *MockCached_ListStatusChangeActions_Call {
	return &MockCached_ListStatusChangeActions_Call{Call: _e.mock.On("ListStatusChangeActions", appId)}
}

func (_c *MockCached_ListStatusChangeActions_Call) Run(run func(appId string)) *MockCached_ListStatusChangeActions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCached_ListStatusChangeActions_Call) Return(actions []api.Action) *MockCached_ListStatusChangeActions_Call {
	_c.Call.Return(actions)
	return _c
}

func (_c *MockCached_ListStatusChangeActions_Call) RunAndReturn(run func(appId string) []api.Action) *MockCached_ListStatusChangeActions_Call {
	_c.Call.Return(run)
	return _c
}
