// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testing

import (
	"github.com/pbloigu/gonfig/server/configurations"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigurations creates a new instance of MockConfigurations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurations {
	mock := &MockConfigurations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigurations is an autogenerated mock type for the Configurations type
type MockConfigurations struct {
	mock.Mock
}

type MockConfigurations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigurations) EXPECT() *MockConfigurations_Expecter {
	return &MockConfigurations_Expecter{mock: &_m.Mock}
}

// DeleteApplication provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) DeleteApplication(id string) {
	_mock.Called(id)
	return
}

// MockConfigurations_DeleteApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApplication'
type MockConfigurations_DeleteApplication_Call struct {
	*mock.Call
}

// DeleteApplication is a helper method to define mock.On call
//   - id string
func (_e *MockConfigurations_Expecter) DeleteApplication(id interface{}) *MockConfigurations_DeleteApplication_Call {
	return &MockConfigurations_DeleteApplication_Call{Call: _e.mock.On("DeleteApplication", id)}
}

func (_c *MockConfigurations_DeleteApplication_Call) Run(run func(id string)) *MockConfigurations_DeleteApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_DeleteApplication_Call) Return() *MockConfigurations_DeleteApplication_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurations_DeleteApplication_Call) RunAndReturn(run func(id string)) *MockConfigurations_DeleteApplication_Call {
	_c.Run(run)
	return _c
}

// DeleteCronTrigger provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) DeleteCronTrigger(id int) {
	_mock.Called(id)
	return
}

// MockConfigurations_DeleteCronTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCronTrigger'
type MockConfigurations_DeleteCronTrigger_Call struct {
	*mock.Call
}

// DeleteCronTrigger is a helper method to define mock.On call
//   - id int
func (_e *MockConfigurations_Expecter) DeleteCronTrigger(id interface{}) *MockConfigurations_DeleteCronTrigger_Call {
	return &MockConfigurations_DeleteCronTrigger_Call{Call: _e.mock.On("DeleteCronTrigger", id)}
}

func (_c *MockConfigurations_DeleteCronTrigger_Call) Run(run func(id int)) *MockConfigurations_DeleteCronTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_DeleteCronTrigger_Call) Return() *MockConfigurations_DeleteCronTrigger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurations_DeleteCronTrigger_Call) RunAndReturn(run func(id int)) *MockConfigurations_DeleteCronTrigger_Call {
	_c.Run(run)
	return _c
}

// DeleteStatusChangeTrigger provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) DeleteStatusChangeTrigger(appId string) {
	_mock.Called(appId)
	return
}

// MockConfigurations_DeleteStatusChangeTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStatusChangeTrigger'
type MockConfigurations_DeleteStatusChangeTrigger_Call struct {
	*mock.Call
}

// DeleteStatusChangeTrigger is a helper method to define mock.On call
//   - appId string
func (_e *MockConfigurations_Expecter) DeleteStatusChangeTrigger(appId interface{}) *MockConfigurations_DeleteStatusChangeTrigger_Call {
	return &MockConfigurations_DeleteStatusChangeTrigger_Call{Call: _e.mock.On("DeleteStatusChangeTrigger", appId)}
}

func (_c *MockConfigurations_DeleteStatusChangeTrigger_Call) Run(run func(appId string)) *MockConfigurations_DeleteStatusChangeTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_DeleteStatusChangeTrigger_Call) Return() *MockConfigurations_DeleteStatusChangeTrigger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurations_DeleteStatusChangeTrigger_Call) RunAndReturn(run func(appId string)) *MockConfigurations_DeleteStatusChangeTrigger_Call {
	_c.Run(run)
	return _c
}

// GetApplication provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) GetApplication(id string) configurations.Application {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetApplication")
	}

	var r0 configurations.Application
	if returnFunc, ok := ret.Get(0).(func(string) configurations.Application); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(configurations.Application)
	}
	return r0
}

// MockConfigurations_GetApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplication'
type MockConfigurations_GetApplication_Call struct {
	*mock.Call
}

// GetApplication is a helper method to define mock.On call
//   - id string
func (_e *MockConfigurations_Expecter) GetApplication(id interface{}) *MockConfigurations_GetApplication_Call {
	return &MockConfigurations_GetApplication_Call{Call: _e.mock.On("GetApplication", id)}
}

func (_c *MockConfigurations_GetApplication_Call) Run(run func(id string)) *MockConfigurations_GetApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_GetApplication_Call) Return(application configurations.Application) *MockConfigurations_GetApplication_Call {
	_c.Call.Return(application)
	return _c
}

func (_c *MockConfigurations_GetApplication_Call) RunAndReturn(run func(id string) configurations.Application) *MockConfigurations_GetApplication_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfiguration provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) GetConfiguration(appId string) configurations.Configuration {
	ret := _mock.Called(appId)

	if len(ret) == 0 {
		panic("no return value specified for GetConfiguration")
	}

	var r0 configurations.Configuration
	if returnFunc, ok := ret.Get(0).(func(string) configurations.Configuration); ok {
		r0 = returnFunc(appId)
	} else {
		r0 = ret.Get(0).(configurations.Configuration)
	}
	return r0
}

// MockConfigurations_GetConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfiguration'
type MockConfigurations_GetConfiguration_Call struct {
	*mock.Call
}

// GetConfiguration is a helper method to define mock.On call
//   - appId string
func (_e *MockConfigurations_Expecter) GetConfiguration(appId interface{}) *MockConfigurations_GetConfiguration_Call {
	return &MockConfigurations_GetConfiguration_Call{Call: _e.mock.On("GetConfiguration", appId)}
}

func (_c *MockConfigurations_GetConfiguration_Call) Run(run func(appId string)) *MockConfigurations_GetConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_GetConfiguration_Call) Return(configuration configurations.Configuration) *MockConfigurations_GetConfiguration_Call {
	_c.Call.Return(configuration)
	return _c
}

func (_c *MockConfigurations_GetConfiguration_Call) RunAndReturn(run func(appId string) configurations.Configuration) *MockConfigurations_GetConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GetCronTrigger provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) GetCronTrigger(id int) configurations.CronTrigger {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCronTrigger")
	}

	var r0 configurations.CronTrigger
	if returnFunc, ok := ret.Get(0).(func(int) configurations.CronTrigger); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(configurations.CronTrigger)
	}
	return r0
}

// MockConfigurations_GetCronTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCronTrigger'
type MockConfigurations_GetCronTrigger_Call struct {
	*mock.Call
}

// GetCronTrigger is a helper method to define mock.On call
//   - id int
func (_e *MockConfigurations_Expecter) GetCronTrigger(id interface{}) *MockConfigurations_GetCronTrigger_Call {
	return &MockConfigurations_GetCronTrigger_Call{Call: _e.mock.On("GetCronTrigger", id)}
}

func (_c *MockConfigurations_GetCronTrigger_Call) Run(run func(id int)) *MockConfigurations_GetCronTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_GetCronTrigger_Call) Return(cronTrigger configurations.CronTrigger) *MockConfigurations_GetCronTrigger_Call {
	_c.Call.Return(cronTrigger)
	return _c
}

func (_c *MockConfigurations_GetCronTrigger_Call) RunAndReturn(run func(id int) configurations.CronTrigger) *MockConfigurations_GetCronTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusChangeActions provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) GetStatusChangeActions(appId string) []configurations.Action {
	ret := _mock.Called(appId)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusChangeActions")
	}

	var r0 []configurations.Action
	if returnFunc, ok := ret.Get(0).(func(string) []configurations.Action); ok {
		r0 = returnFunc(appId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]configurations.Action)
		}
	}
	return r0
}

// MockConfigurations_GetStatusChangeActions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusChangeActions'
type MockConfigurations_GetStatusChangeActions_Call struct {
	*mock.Call
}

// GetStatusChangeActions is a helper method to define mock.On call
//   - appId string
func (_e *MockConfigurations_Expecter) GetStatusChangeActions(appId interface{}) *MockConfigurations_GetStatusChangeActions_Call {
	return &MockConfigurations_GetStatusChangeActions_Call{Call: _e.mock.On("GetStatusChangeActions", appId)}
}

func (_c *MockConfigurations_GetStatusChangeActions_Call) Run(run func(appId string)) *MockConfigurations_GetStatusChangeActions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_GetStatusChangeActions_Call) Return(actions []configurations.Action) *MockConfigurations_GetStatusChangeActions_Call {
	_c.Call.Return(actions)
	return _c
}

func (_c *MockConfigurations_GetStatusChangeActions_Call) RunAndReturn(run func(appId string) []configurations.Action) *MockConfigurations_GetStatusChangeActions_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusChangeTrigger provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) GetStatusChangeTrigger(appId string) configurations.StatusChangeTrigger {
	ret := _mock.Called(appId)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusChangeTrigger")
	}

	var r0 configurations.StatusChangeTrigger
	if returnFunc, ok := ret.Get(0).(func(string) configurations.StatusChangeTrigger); ok {
		r0 = returnFunc(appId)
	} else {
		r0 = ret.Get(0).(configurations.StatusChangeTrigger)
	}
	return r0
}

// MockConfigurations_GetStatusChangeTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusChangeTrigger'
type MockConfigurations_GetStatusChangeTrigger_Call struct {
	*mock.Call
}

// GetStatusChangeTrigger is a helper method to define mock.On call
//   - appId string
func (_e *MockConfigurations_Expecter) GetStatusChangeTrigger(appId interface{}) *MockConfigurations_GetStatusChangeTrigger_Call {
	return &MockConfigurations_GetStatusChangeTrigger_Call{Call: _e.mock.On("GetStatusChangeTrigger", appId)}
}

func (_c *MockConfigurations_GetStatusChangeTrigger_Call) Run(run func(appId string)) *MockConfigurations_GetStatusChangeTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_GetStatusChangeTrigger_Call) Return(statusChangeTrigger configurations.StatusChangeTrigger) *MockConfigurations_GetStatusChangeTrigger_Call {
	_c.Call.Return(statusChangeTrigger)
	return _c
}

func (_c *MockConfigurations_GetStatusChangeTrigger_Call) RunAndReturn(run func(appId string) configurations.StatusChangeTrigger) *MockConfigurations_GetStatusChangeTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// IsAllowed provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) IsAllowed(id string, apiKey string) bool {
	ret := _mock.Called(id, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(id, apiKey)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfigurations_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type MockConfigurations_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - id string
//   - apiKey string
func (_e *MockConfigurations_Expecter) IsAllowed(id interface{}, apiKey interface{}) *MockConfigurations_IsAllowed_Call {
	return &MockConfigurations_IsAllowed_Call{Call: _e.mock.On("IsAllowed", id, apiKey)}
}

func (_c *MockConfigurations_IsAllowed_Call) Run(run func(id string, apiKey string)) *MockConfigurations_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigurations_IsAllowed_Call) Return(b bool) *MockConfigurations_IsAllowed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfigurations_IsAllowed_Call) RunAndReturn(run func(id string, apiKey string) bool) *MockConfigurations_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// ListApplicationIds provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) ListApplicationIds() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListApplicationIds")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockConfigurations_ListApplicationIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApplicationIds'
type MockConfigurations_ListApplicationIds_Call struct {
	*mock.Call
}

// ListApplicationIds is a helper method to define mock.On call
func (_e *MockConfigurations_Expecter) ListApplicationIds() *MockConfigurations_ListApplicationIds_Call {
	return &MockConfigurations_ListApplicationIds_Call{Call: _e.mock.On("ListApplicationIds")}
}

func (_c *MockConfigurations_ListApplicationIds_Call) Run(run func()) *MockConfigurations_ListApplicationIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigurations_ListApplicationIds_Call) Return(strings []string) *MockConfigurations_ListApplicationIds_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockConfigurations_ListApplicationIds_Call) RunAndReturn(run func() []string) *MockConfigurations_ListApplicationIds_Call {
	_c.Call.Return(run)
	return _c
}

// ListApplications provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) ListApplications() []configurations.Application {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListApplications")
	}

	var r0 []configurations.Application
	if returnFunc, ok := ret.Get(0).(func() []configurations.Application); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]configurations.Application)
		}
	}
	return r0
}

// MockConfigurations_ListApplications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApplications'
type MockConfigurations_ListApplications_Call struct {
	*mock.Call
}

// ListApplications is a helper method to define mock.On call
func (_e *MockConfigurations_Expecter) ListApplications() *MockConfigurations_ListApplications_Call {
	return &MockConfigurations_ListApplications_Call{Call: _e.mock.On("ListApplications")}
}

func (_c *MockConfigurations_ListApplications_Call) Run(run func()) *MockConfigurations_ListApplications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigurations_ListApplications_Call) Return(applications []configurations.Application) *MockConfigurations_ListApplications_Call {
	_c.Call.Return(applications)
	return _c
}

func (_c *MockConfigurations_ListApplications_Call) RunAndReturn(run func() []configurations.Application) *MockConfigurations_ListApplications_Call {
	_c.Call.Return(run)
	return _c
}

// ListCronTriggers provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) ListCronTriggers() []configurations.CronTrigger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListCronTriggers")
	}

	var r0 []configurations.CronTrigger
	if returnFunc, ok := ret.Get(0).(func() []configurations.CronTrigger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]configurations.CronTrigger)
		}
	}
	return r0
}

// MockConfigurations_ListCronTriggers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCronTriggers'
type MockConfigurations_ListCronTriggers_Call struct {
	*mock.Call
}

// ListCronTriggers is a helper method to define mock.On call
func (_e *MockConfigurations_Expecter) ListCronTriggers() *MockConfigurations_ListCronTriggers_Call {
	return &MockConfigurations_ListCronTriggers_Call{Call: _e.mock.On("ListCronTriggers")}
}

func (_c *MockConfigurations_ListCronTriggers_Call) Run(run func()) *MockConfigurations_ListCronTriggers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigurations_ListCronTriggers_Call) Return(cronTriggers []configurations.CronTrigger) *MockConfigurations_ListCronTriggers_Call {
	_c.Call.Return(cronTriggers)
	return _c
}

func (_c *MockConfigurations_ListCronTriggers_Call) RunAndReturn(run func() []configurations.CronTrigger) *MockConfigurations_ListCronTriggers_Call {
	_c.Call.Return(run)
	return _c
}

// ListSeriesTriggers provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) ListSeriesTriggers(appId string) []configurations.SeriesTrigger {
	ret := _mock.Called(appId)

	if len(ret) == 0 {
		panic("no return value specified for ListSeriesTriggers")
	}

	var r0 []configurations.SeriesTrigger
	if returnFunc, ok := ret.Get(0).(func(string) []configurations.SeriesTrigger); ok {
		r0 = returnFunc(appId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]configurations.SeriesTrigger)
		}
	}
	return r0
}

// MockConfigurations_ListSeriesTriggers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSeriesTriggers'
type MockConfigurations_ListSeriesTriggers_Call struct {
	*mock.Call
}

// ListSeriesTriggers is a helper method to define mock.On call
//   - appId string
func (_e *MockConfigurations_Expecter) ListSeriesTriggers(appId interface{}) *MockConfigurations_ListSeriesTriggers_Call {
	return &MockConfigurations_ListSeriesTriggers_Call{Call: _e.mock.On("ListSeriesTriggers", appId)}
}

func (_c *MockConfigurations_ListSeriesTriggers_Call) Run(run func(appId string)) *MockConfigurations_ListSeriesTriggers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_ListSeriesTriggers_Call) Return(seriesTriggers []configurations.SeriesTrigger) *MockConfigurations_ListSeriesTriggers_Call {
	_c.Call.Return(seriesTriggers)
	return _c
}

func (_c *MockConfigurations_ListSeriesTriggers_Call) RunAndReturn(run func(appId string) []configurations.SeriesTrigger) *MockConfigurations_ListSeriesTriggers_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) Login(login string, password string) bool {
	ret := _mock.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(login, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfigurations_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockConfigurations_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - login string
//   - password string
func (_e *MockConfigurations_Expecter) Login(login interface{}, password interface{}) *MockConfigurations_Login_Call {
	return &MockConfigurations_Login_Call{Call: _e.mock.On("Login", login, password)}
}

func (_c *MockConfigurations_Login_Call) Run(run func(login string, password string)) *MockConfigurations_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigurations_Login_Call) Return(b bool) *MockConfigurations_Login_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfigurations_Login_Call) RunAndReturn(run func(login string, password string) bool) *MockConfigurations_Login_Call {
	_c.Call.Return(run)
	return _c
}

// PersistApplication provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) PersistApplication(a configurations.Application) configurations.Application {
	ret := _mock.Called(a)

	if len(ret) == 0 {
		panic("no return value specified for PersistApplication")
	}

	var r0 configurations.Application
	if returnFunc, ok := ret.Get(0).(func(configurations.Application) configurations.Application); ok {
		r0 = returnFunc(a)
	} else {
		r0 = ret.Get(0).(configurations.Application)
	}
	return r0
}

// MockConfigurations_PersistApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistApplication'
type MockConfigurations_PersistApplication_Call struct {
	*mock.Call
}

// PersistApplication is a helper method to define mock.On call
//   - a configurations.Application
func (_e *MockConfigurations_Expecter) PersistApplication(a interface{}) *MockConfigurations_PersistApplication_Call {
	return &MockConfigurations_PersistApplication_Call{Call: _e.mock.On("PersistApplication", a)}
}

func (_c *MockConfigurations_PersistApplication_Call) Run(run func(a configurations.Application)) *MockConfigurations_PersistApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 configurations.Application
		if args[0] != nil {
			arg0 = args[0].(configurations.Application)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_PersistApplication_Call) Return(application configurations.Application) *MockConfigurations_PersistApplication_Call {
	_c.Call.Return(application)
	return _c
}

func (_c *MockConfigurations_PersistApplication_Call) RunAndReturn(run func(a configurations.Application) configurations.Application) *MockConfigurations_PersistApplication_Call {
	_c.Call.Return(run)
	return _c
}

// PersistConfiguration provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) PersistConfiguration(applicationId string, c configurations.Configuration) {
	_mock.Called(applicationId, c)
	return
}

// MockConfigurations_PersistConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistConfiguration'
type MockConfigurations_PersistConfiguration_Call struct {
	*mock.Call
}

// PersistConfiguration is a helper method to define mock.On call
//   - applicationId string
//   - c configurations.Configuration
func (_e *MockConfigurations_Expecter) PersistConfiguration(applicationId interface{}, c interface{}) *MockConfigurations_PersistConfiguration_Call {
	return &MockConfigurations_PersistConfiguration_Call{Call: _e.mock.On("PersistConfiguration", applicationId, c)}
}

func (_c *MockConfigurations_PersistConfiguration_Call) Run(run func(applicationId string, c configurations.Configuration)) *MockConfigurations_PersistConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 configurations.Configuration
		if args[1] != nil {
			arg1 = args[1].(configurations.Configuration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigurations_PersistConfiguration_Call) Return() *MockConfigurations_PersistConfiguration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurations_PersistConfiguration_Call) RunAndReturn(run func(applicationId string, c configurations.Configuration)) *MockConfigurations_PersistConfiguration_Call {
	_c.Run(run)
	return _c
}

// PersistCronTrigger provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) PersistCronTrigger(cr configurations.CronTrigger) configurations.CronTrigger {
	ret := _mock.Called(cr)

	if len(ret) == 0 {
		panic("no return value specified for PersistCronTrigger")
	}

	var r0 configurations.CronTrigger
	if returnFunc, ok := ret.Get(0).(func(configurations.CronTrigger) configurations.CronTrigger); ok {
		r0 = returnFunc(cr)
	} else {
		r0 = ret.Get(0).(configurations.CronTrigger)
	}
	return r0
}

// MockConfigurations_PersistCronTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistCronTrigger'
type MockConfigurations_PersistCronTrigger_Call struct {
	*mock.Call
}

// PersistCronTrigger is a helper method to define mock.On call
//   - cr configurations.CronTrigger
func (_e *MockConfigurations_Expecter) PersistCronTrigger(cr interface{}) *MockConfigurations_PersistCronTrigger_Call {
	return &MockConfigurations_PersistCronTrigger_Call{Call: _e.mock.On("PersistCronTrigger", cr)}
}

func (_c *MockConfigurations_PersistCronTrigger_Call) Run(run func(cr configurations.CronTrigger)) *MockConfigurations_PersistCronTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 configurations.CronTrigger
		if args[0] != nil {
			arg0 = args[0].(configurations.CronTrigger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_PersistCronTrigger_Call) Return(cronTrigger configurations.CronTrigger) *MockConfigurations_PersistCronTrigger_Call {
	_c.Call.Return(cronTrigger)
	return _c
}

func (_c *MockConfigurations_PersistCronTrigger_Call) RunAndReturn(run func(cr configurations.CronTrigger) configurations.CronTrigger) *MockConfigurations_PersistCronTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// PersistSeriesTrigger provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) PersistSeriesTrigger(appId string, mt configurations.SeriesTrigger) {
	_mock.Called(appId, mt)
	return
}

// MockConfigurations_PersistSeriesTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistSeriesTrigger'
type MockConfigurations_PersistSeriesTrigger_Call struct {
	*mock.Call
}

// PersistSeriesTrigger is a helper method to define mock.On call
//   - appId string
//   - mt configurations.SeriesTrigger
func (_e *MockConfigurations_Expecter) PersistSeriesTrigger(appId interface{}, mt interface{}) *MockConfigurations_PersistSeriesTrigger_Call {
	return &MockConfigurations_PersistSeriesTrigger_Call{Call: _e.mock.On("PersistSeriesTrigger", appId, mt)}
}

func (_c *MockConfigurations_PersistSeriesTrigger_Call) Run(run func(appId string, mt configurations.SeriesTrigger)) *MockConfigurations_PersistSeriesTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 configurations.SeriesTrigger
		if args[1] != nil {
			arg1 = args[1].(configurations.SeriesTrigger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigurations_PersistSeriesTrigger_Call) Return() *MockConfigurations_PersistSeriesTrigger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurations_PersistSeriesTrigger_Call) RunAndReturn(run func(appId string, mt configurations.SeriesTrigger)) *MockConfigurations_PersistSeriesTrigger_Call {
	_c.Run(run)
	return _c
}

// PersistStatusChangeTrigger provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) PersistStatusChangeTrigger(appId string, st configurations.StatusChangeTrigger) configurations.StatusChangeTrigger {
	ret := _mock.Called(appId, st)

	if len(ret) == 0 {
		panic("no return value specified for PersistStatusChangeTrigger")
	}

	var r0 configurations.StatusChangeTrigger
	if returnFunc, ok := ret.Get(0).(func(string, configurations.StatusChangeTrigger) configurations.StatusChangeTrigger); ok {
		r0 = returnFunc(appId, st)
	} else {
		r0 = ret.Get(0).(configurations.StatusChangeTrigger)
	}
	return r0
}

// MockConfigurations_PersistStatusChangeTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistStatusChangeTrigger'
type MockConfigurations_PersistStatusChangeTrigger_Call struct {
	*mock.Call
}

// PersistStatusChangeTrigger is a helper method to define mock.On call
//   - appId string
//   - st configurations.StatusChangeTrigger
func (_e *MockConfigurations_Expecter) PersistStatusChangeTrigger(appId interface{}, st interface{}) *MockConfigurations_PersistStatusChangeTrigger_Call {
	return &MockConfigurations_PersistStatusChangeTrigger_Call{Call: _e.mock.On("PersistStatusChangeTrigger", appId, st)}
}

func (_c *MockConfigurations_PersistStatusChangeTrigger_Call) Run(run func(appId string, st configurations.StatusChangeTrigger)) *MockConfigurations_PersistStatusChangeTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 configurations.StatusChangeTrigger
		if args[1] != nil {
			arg1 = args[1].(configurations.StatusChangeTrigger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigurations_PersistStatusChangeTrigger_Call) Return(statusChangeTrigger configurations.StatusChangeTrigger) *MockConfigurations_PersistStatusChangeTrigger_Call {
	_c.Call.Return(statusChangeTrigger)
	return _c
}

func (_c *MockConfigurations_PersistStatusChangeTrigger_Call) RunAndReturn(run func(appId string, st configurations.StatusChangeTrigger) configurations.StatusChangeTrigger) *MockConfigurations_PersistStatusChangeTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateApplication provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) UpdateApplication(a configurations.Application) {
	_mock.Called(a)
	return
}

// MockConfigurations_UpdateApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateApplication'
type MockConfigurations_UpdateApplication_Call struct {
	*mock.Call
}

// UpdateApplication is a helper method to define mock.On call
//   - a configurations.Application
func (_e *MockConfigurations_Expecter) UpdateApplication(a interface{}) *MockConfigurations_UpdateApplication_Call {
	return &MockConfigurations_UpdateApplication_Call{Call: _e.mock.On("UpdateApplication", a)}
}

func (_c *MockConfigurations_UpdateApplication_Call) Run(run func(a configurations.Application)) *MockConfigurations_UpdateApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 configurations.Application
		if args[0] != nil {
			arg0 = args[0].(configurations.Application)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_UpdateApplication_Call) Return() *MockConfigurations_UpdateApplication_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurations_UpdateApplication_Call) RunAndReturn(run func(a configurations.Application)) *MockConfigurations_UpdateApplication_Call {
	_c.Run(run)
	return _c
}

// UpdateCronTrigger provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) UpdateCronTrigger(cr configurations.CronTrigger) {
	_mock.Called(cr)
	return
}

// MockConfigurations_UpdateCronTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCronTrigger'
type MockConfigurations_UpdateCronTrigger_Call struct {
	*mock.Call
}

// UpdateCronTrigger is a helper method to define mock.On call
//   - cr configurations.CronTrigger
func (_e *MockConfigurations_Expecter) UpdateCronTrigger(cr interface{}) *MockConfigurations_UpdateCronTrigger_Call {
	return &MockConfigurations_UpdateCronTrigger_Call{Call: _e.mock.On("UpdateCronTrigger", cr)}
}

func (_c *MockConfigurations_UpdateCronTrigger_Call) Run(run func(cr configurations.CronTrigger)) *MockConfigurations_UpdateCronTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 configurations.CronTrigger
		if args[0] != nil {
			arg0 = args[0].(configurations.CronTrigger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurations_UpdateCronTrigger_Call) Return() *MockConfigurations_UpdateCronTrigger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurations_UpdateCronTrigger_Call) RunAndReturn(run func(cr configurations.CronTrigger)) *MockConfigurations_UpdateCronTrigger_Call {
	_c.Run(run)
	return _c
}

// UpdateStatusChangeTrigger provides a mock function for the type MockConfigurations
func (_mock *MockConfigurations) UpdateStatusChangeTrigger(appId string, t configurations.StatusChangeTrigger) {
	_mock.Called(appId, t)
	return
}

// MockConfigurations_UpdateStatusChangeTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusChangeTrigger'
type MockConfigurations_UpdateStatusChangeTrigger_Call struct {
	*mock.Call
}

// UpdateStatusChangeTrigger is a helper method to define mock.On call
//   - appId string
//   - t configurations.StatusChangeTrigger
func (_e *MockConfigurations_Expecter) UpdateStatusChangeTrigger(appId interface{}, t interface{}) *MockConfigurations_UpdateStatusChangeTrigger_Call {
	return &MockConfigurations_UpdateStatusChangeTrigger_Call{Call: _e.mock.On("UpdateStatusChangeTrigger", appId, t)}
}

func (_c *MockConfigurations_UpdateStatusChangeTrigger_Call) Run(run func(appId string, t configurations.StatusChangeTrigger)) *MockConfigurations_UpdateStatusChangeTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 configurations.StatusChangeTrigger
		if args[1] != nil {
			arg1 = args[1].(configurations.StatusChangeTrigger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigurations_UpdateStatusChangeTrigger_Call) Return() *MockConfigurations_UpdateStatusChangeTrigger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurations_UpdateStatusChangeTrigger_Call) RunAndReturn(run func(appId string, t configurations.StatusChangeTrigger)) *MockConfigurations_UpdateStatusChangeTrigger_Call {
	_c.Run(run)
	return _c
}
