// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testing

import (
	"github.com/pbloigu/gonfig/api"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduler creates a new instance of MockScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduler {
	mock := &MockScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduler is an autogenerated mock type for the Scheduler type
type MockScheduler struct {
	mock.Mock
}

type MockScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduler) EXPECT() *MockScheduler_Expecter {
	return &MockScheduler_Expecter{mock: &_m.Mock}
}

// DeregisterCronTrigger provides a mock function for the type MockScheduler
func (_mock *MockScheduler) DeregisterCronTrigger(id int) {
	_mock.Called(id)
	return
}

// MockScheduler_DeregisterCronTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeregisterCronTrigger'
type MockScheduler_DeregisterCronTrigger_Call struct {
	*mock.Call
}

// DeregisterCronTrigger is a helper method to define mock.On call
//   - id int
func (_e *MockScheduler_Expecter) DeregisterCronTrigger(id interface{}) *MockScheduler_DeregisterCronTrigger_Call {
	return &MockScheduler_DeregisterCronTrigger_Call{Call: _e.mock.On("DeregisterCronTrigger", id)}
}

func (_c *MockScheduler_DeregisterCronTrigger_Call) Run(run func(id int)) *MockScheduler_DeregisterCronTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScheduler_DeregisterCronTrigger_Call) Return() *MockScheduler_DeregisterCronTrigger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockScheduler_DeregisterCronTrigger_Call) RunAndReturn(run func(id int)) *MockScheduler_DeregisterCronTrigger_Call {
	_c.Run(run)
	return _c
}

// RegisterCronTrigger provides a mock function for the type MockScheduler
func (_mock *MockScheduler) RegisterCronTrigger(trigger api.CronTrigger) {
	_mock.Called(trigger)
	return
}

// MockScheduler_RegisterCronTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterCronTrigger'
type MockScheduler_RegisterCronTrigger_Call struct {
	*mock.Call
}

// RegisterCronTrigger is a helper method to define mock.On call
//   - trigger api.CronTrigger
func (_e *MockScheduler_Expecter) RegisterCronTrigger(trigger interface{}) *MockScheduler_RegisterCronTrigger_Call {
	return &MockScheduler_RegisterCronTrigger_Call{Call: _e.mock.On("RegisterCronTrigger", trigger)}
}

func (_c *MockScheduler_RegisterCronTrigger_Call) Run(run func(trigger api.CronTrigger)) *MockScheduler_RegisterCronTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.CronTrigger
		if args[0] != nil {
			arg0 = args[0].(api.CronTrigger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScheduler_RegisterCronTrigger_Call) Return() *MockScheduler_RegisterCronTrigger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockScheduler_RegisterCronTrigger_Call) RunAndReturn(run func(trigger api.CronTrigger)) *MockScheduler_RegisterCronTrigger_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockScheduler
func (_mock *MockScheduler) Start() {
	_mock.Called()
	return
}

// MockScheduler_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockScheduler_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockScheduler_Expecter) Start() *MockScheduler_Start_Call {
	return &MockScheduler_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockScheduler_Start_Call) Run(run func()) *MockScheduler_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScheduler_Start_Call) Return() *MockScheduler_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockScheduler_Start_Call) RunAndReturn(run func()) *MockScheduler_Start_Call {
	_c.Run(run)
	return _c
}
