// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testing

import (
	"github.com/pbloigu/gonfig/server/series"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSeriesDb creates a new instance of MockSeriesDb. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeriesDb(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeriesDb {
	mock := &MockSeriesDb{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSeriesDb is an autogenerated mock type for the SeriesDb type
type MockSeriesDb struct {
	mock.Mock
}

type MockSeriesDb_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeriesDb) EXPECT() *MockSeriesDb_Expecter {
	return &MockSeriesDb_Expecter{mock: &_m.Mock}
}

// CountSeriesValues provides a mock function for the type MockSeriesDb
func (_mock *MockSeriesDb) CountSeriesValues(seriesId int) int {
	ret := _mock.Called(seriesId)

	if len(ret) == 0 {
		panic("no return value specified for CountSeriesValues")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(int) int); ok {
		r0 = returnFunc(seriesId)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockSeriesDb_CountSeriesValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSeriesValues'
type MockSeriesDb_CountSeriesValues_Call struct {
	*mock.Call
}

// CountSeriesValues is a helper method to define mock.On call
//   - seriesId int
func (_e *MockSeriesDb_Expecter) CountSeriesValues(seriesId interface{}) *MockSeriesDb_CountSeriesValues_Call {
	return &MockSeriesDb_CountSeriesValues_Call{Call: _e.mock.On("CountSeriesValues", seriesId)}
}

func (_c *MockSeriesDb_CountSeriesValues_Call) Run(run func(seriesId int)) *MockSeriesDb_CountSeriesValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSeriesDb_CountSeriesValues_Call) Return(n int) *MockSeriesDb_CountSeriesValues_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockSeriesDb_CountSeriesValues_Call) RunAndReturn(run func(seriesId int) int) *MockSeriesDb_CountSeriesValues_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteApplication provides a mock function for the type MockSeriesDb
func (_mock *MockSeriesDb) DeleteApplication(id string) {
	_mock.Called(id)
	return
}

// MockSeriesDb_DeleteApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApplication'
type MockSeriesDb_DeleteApplication_Call struct {
	*mock.Call
}

// DeleteApplication is a helper method to define mock.On call
//   - id string
func (_e *MockSeriesDb_Expecter) DeleteApplication(id interface{}) *MockSeriesDb_DeleteApplication_Call {
	return &MockSeriesDb_DeleteApplication_Call{Call: _e.mock.On("DeleteApplication", id)}
}

func (_c *MockSeriesDb_DeleteApplication_Call) Run(run func(id string)) *MockSeriesDb_DeleteApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSeriesDb_DeleteApplication_Call) Return() *MockSeriesDb_DeleteApplication_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSeriesDb_DeleteApplication_Call) RunAndReturn(run func(id string)) *MockSeriesDb_DeleteApplication_Call {
	_c.Run(run)
	return _c
}

// GetSeries provides a mock function for the type MockSeriesDb
func (_mock *MockSeriesDb) GetSeries(applicationId string, seriesName string) series.Series {
	ret := _mock.Called(applicationId, seriesName)

	if len(ret) == 0 {
		panic("no return value specified for GetSeries")
	}

	var r0 series.Series
	if returnFunc, ok := ret.Get(0).(func(string, string) series.Series); ok {
		r0 = returnFunc(applicationId, seriesName)
	} else {
		r0 = ret.Get(0).(series.Series)
	}
	return r0
}

// MockSeriesDb_GetSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeries'
type MockSeriesDb_GetSeries_Call struct {
	*mock.Call
}

// GetSeries is a helper method to define mock.On call
//   - applicationId string
//   - seriesName string
func (_e *MockSeriesDb_Expecter) GetSeries(applicationId interface{}, seriesName interface{}) *MockSeriesDb_GetSeries_Call {
	return &MockSeriesDb_GetSeries_Call{Call: _e.mock.On("GetSeries", applicationId, seriesName)}
}

func (_c *MockSeriesDb_GetSeries_Call) Run(run func(applicationId string, seriesName string)) *MockSeriesDb_GetSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeriesDb_GetSeries_Call) Return(series1 series.Series) *MockSeriesDb_GetSeries_Call {
	_c.Call.Return(series1)
	return _c
}

func (_c *MockSeriesDb_GetSeries_Call) RunAndReturn(run func(applicationId string, seriesName string) series.Series) *MockSeriesDb_GetSeries_Call {
	_c.Call.Return(run)
	return _c
}

// InitSeries provides a mock function for the type MockSeriesDb
func (_mock *MockSeriesDb) InitSeries(applicationId string, seriesName string) {
	_mock.Called(applicationId, seriesName)
	return
}

// MockSeriesDb_InitSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitSeries'
type MockSeriesDb_InitSeries_Call struct {
	*mock.Call
}

// InitSeries is a helper method to define mock.On call
//   - applicationId string
//   - seriesName string
func (_e *MockSeriesDb_Expecter) InitSeries(applicationId interface{}, seriesName interface{}) *MockSeriesDb_InitSeries_Call {
	return &MockSeriesDb_InitSeries_Call{Call: _e.mock.On("InitSeries", applicationId, seriesName)}
}

func (_c *MockSeriesDb_InitSeries_Call) Run(run func(applicationId string, seriesName string)) *MockSeriesDb_InitSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeriesDb_InitSeries_Call) Return() *MockSeriesDb_InitSeries_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSeriesDb_InitSeries_Call) RunAndReturn(run func(applicationId string, seriesName string)) *MockSeriesDb_InitSeries_Call {
	_c.Run(run)
	return _c
}

// ListSeries provides a mock function for the type MockSeriesDb
func (_mock *MockSeriesDb) ListSeries(applicationId string) []series.Series {
	ret := _mock.Called(applicationId)

	if len(ret) == 0 {
		panic("no return value specified for ListSeries")
	}

	var r0 []series.Series
	if returnFunc, ok := ret.Get(0).(func(string) []series.Series); ok {
		r0 = returnFunc(applicationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]series.Series)
		}
	}
	return r0
}

// MockSeriesDb_ListSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSeries'
type MockSeriesDb_ListSeries_Call struct {
	*mock.Call
}

// ListSeries is a helper method to define mock.On call
//   - applicationId string
func (_e *MockSeriesDb_Expecter) ListSeries(applicationId interface{}) *MockSeriesDb_ListSeries_Call {
	return &MockSeriesDb_ListSeries_Call{Call: _e.mock.On("ListSeries", applicationId)}
}

func (_c *MockSeriesDb_ListSeries_Call) Run(run func(applicationId string)) *MockSeriesDb_ListSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSeriesDb_ListSeries_Call) Return(seriess []series.Series) *MockSeriesDb_ListSeries_Call {
	_c.Call.Return(seriess)
	return _c
}

func (_c *MockSeriesDb_ListSeries_Call) RunAndReturn(run func(applicationId string) []series.Series) *MockSeriesDb_ListSeries_Call {
	_c.Call.Return(run)
	return _c
}

// ListSeriesValues provides a mock function for the type MockSeriesDb
func (_mock *MockSeriesDb) ListSeriesValues(seriesId int, sort series.Sort, pagination series.Pagination) []series.SeriesValue {
	ret := _mock.Called(seriesId, sort, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListSeriesValues")
	}

	var r0 []series.SeriesValue
	if returnFunc, ok := ret.Get(0).(func(int, series.Sort, series.Pagination) []series.SeriesValue); ok {
		r0 = returnFunc(seriesId, sort, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]series.SeriesValue)
		}
	}
	return r0
}

// MockSeriesDb_ListSeriesValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSeriesValues'
type MockSeriesDb_ListSeriesValues_Call struct {
	*mock.Call
}

// ListSeriesValues is a helper method to define mock.On call
//   - seriesId int
//   - sort series.Sort
//   - pagination series.Pagination
func (_e *MockSeriesDb_Expecter) ListSeriesValues(seriesId interface{}, sort interface{}, pagination interface{}) *MockSeriesDb_ListSeriesValues_Call {
	return &MockSeriesDb_ListSeriesValues_Call{Call: _e.mock.On("ListSeriesValues", seriesId, sort, pagination)}
}

func (_c *MockSeriesDb_ListSeriesValues_Call) Run(run func(seriesId int, sort series.Sort, pagination series.Pagination)) *MockSeriesDb_ListSeriesValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 series.Sort
		if args[1] != nil {
			arg1 = args[1].(series.Sort)
		}
		var arg2 series.Pagination
		if args[2] != nil {
			arg2 = args[2].(series.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSeriesDb_ListSeriesValues_Call) Return(seriesValues []series.SeriesValue) *MockSeriesDb_ListSeriesValues_Call {
	_c.Call.Return(seriesValues)
	return _c
}

func (_c *MockSeriesDb_ListSeriesValues_Call) RunAndReturn(run func(seriesId int, sort series.Sort, pagination series.Pagination) []series.SeriesValue) *MockSeriesDb_ListSeriesValues_Call {
	_c.Call.Return(run)
	return _c
}

// PeristSeriesValue provides a mock function for the type MockSeriesDb
func (_mock *MockSeriesDb) PeristSeriesValue(applicationId string, seriesName string, value series.SeriesValue) {
	_mock.Called(applicationId, seriesName, value)
	return
}

// MockSeriesDb_PeristSeriesValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeristSeriesValue'
type MockSeriesDb_PeristSeriesValue_Call struct {
	*mock.Call
}

// PeristSeriesValue is a helper method to define mock.On call
//   - applicationId string
//   - seriesName string
//   - value series.SeriesValue
func (_e *MockSeriesDb_Expecter) PeristSeriesValue(applicationId interface{}, seriesName interface{}, value interface{}) *MockSeriesDb_PeristSeriesValue_Call {
	return &MockSeriesDb_PeristSeriesValue_Call{Call: _e.mock.On("PeristSeriesValue", applicationId, seriesName, value)}
}

func (_c *MockSeriesDb_PeristSeriesValue_Call) Run(run func(applicationId string, seriesName string, value series.SeriesValue)) *MockSeriesDb_PeristSeriesValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 series.SeriesValue
		if args[2] != nil {
			arg2 = args[2].(series.SeriesValue)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSeriesDb_PeristSeriesValue_Call) Return() *MockSeriesDb_PeristSeriesValue_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSeriesDb_PeristSeriesValue_Call) RunAndReturn(run func(applicationId string, seriesName string, value series.SeriesValue)) *MockSeriesDb_PeristSeriesValue_Call {
	_c.Run(run)
	return _c
}
