// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testing

import (
	"github.com/pbloigu/gonfig/api"
	"github.com/pbloigu/gonfig/server/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddApplication provides a mock function for the type MockService
func (_mock *MockService) AddApplication(application api.Application) api.Application {
	ret := _mock.Called(application)

	if len(ret) == 0 {
		panic("no return value specified for AddApplication")
	}

	var r0 api.Application
	if returnFunc, ok := ret.Get(0).(func(api.Application) api.Application); ok {
		r0 = returnFunc(application)
	} else {
		r0 = ret.Get(0).(api.Application)
	}
	return r0
}

// MockService_AddApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddApplication'
type MockService_AddApplication_Call struct {
	*mock.Call
}

// AddApplication is a helper method to define mock.On call
//   - application api.Application
func (_e *MockService_Expecter) AddApplication(application interface{}) *MockService_AddApplication_Call {
	return &MockService_AddApplication_Call{Call: _e.mock.On("AddApplication", application)}
}

func (_c *MockService_AddApplication_Call) Run(run func(application api.Application)) *MockService_AddApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.Application
		if args[0] != nil {
			arg0 = args[0].(api.Application)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_AddApplication_Call) Return(application1 api.Application) *MockService_AddApplication_Call {
	_c.Call.Return(application1)
	return _c
}

func (_c *MockService_AddApplication_Call) RunAndReturn(run func(application api.Application) api.Application) *MockService_AddApplication_Call {
	_c.Call.Return(run)
	return _c
}

// AddConfiguration provides a mock function for the type MockService
func (_mock *MockService) AddConfiguration(appId string, configuration api.Configuration) {
	_mock.Called(appId, configuration)
	return
}

// MockService_AddConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConfiguration'
type MockService_AddConfiguration_Call struct {
	*mock.Call
}

// AddConfiguration is a helper method to define mock.On call
//   - appId string
//   - configuration api.Configuration
func (_e *MockService_Expecter) AddConfiguration(appId interface{}, configuration interface{}) *MockService_AddConfiguration_Call {
	return &MockService_AddConfiguration_Call{Call: _e.mock.On("AddConfiguration", appId, configuration)}
}

func (_c *MockService_AddConfiguration_Call) Run(run func(appId string, configuration api.Configuration)) *MockService_AddConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 api.Configuration
		if args[1] != nil {
			arg1 = args[1].(api.Configuration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_AddConfiguration_Call) Return() *MockService_AddConfiguration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_AddConfiguration_Call) RunAndReturn(run func(appId string, configuration api.Configuration)) *MockService_AddConfiguration_Call {
	_c.Run(run)
	return _c
}

// AddCronTrigger provides a mock function for the type MockService
func (_mock *MockService) AddCronTrigger(trigger api.CronTrigger) api.CronTrigger {
	ret := _mock.Called(trigger)

	if len(ret) == 0 {
		panic("no return value specified for AddCronTrigger")
	}

	var r0 api.CronTrigger
	if returnFunc, ok := ret.Get(0).(func(api.CronTrigger) api.CronTrigger); ok {
		r0 = returnFunc(trigger)
	} else {
		r0 = ret.Get(0).(api.CronTrigger)
	}
	return r0
}

// MockService_AddCronTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCronTrigger'
type MockService_AddCronTrigger_Call struct {
	*mock.Call
}

// AddCronTrigger is a helper method to define mock.On call
//   - trigger api.CronTrigger
func (_e *MockService_Expecter) AddCronTrigger(trigger interface{}) *MockService_AddCronTrigger_Call {
	return &MockService_AddCronTrigger_Call{Call: _e.mock.On("AddCronTrigger", trigger)}
}

func (_c *MockService_AddCronTrigger_Call) Run(run func(trigger api.CronTrigger)) *MockService_AddCronTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.CronTrigger
		if args[0] != nil {
			arg0 = args[0].(api.CronTrigger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_AddCronTrigger_Call) Return(cronTrigger api.CronTrigger) *MockService_AddCronTrigger_Call {
	_c.Call.Return(cronTrigger)
	return _c
}

func (_c *MockService_AddCronTrigger_Call) RunAndReturn(run func(trigger api.CronTrigger) api.CronTrigger) *MockService_AddCronTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// AddSeriesValue provides a mock function for the type MockService
func (_mock *MockService) AddSeriesValue(appId string, seriesName string, value api.SeriesValue) {
	_mock.Called(appId, seriesName, value)
	return
}

// MockService_AddSeriesValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSeriesValue'
type MockService_AddSeriesValue_Call struct {
	*mock.Call
}

// AddSeriesValue is a helper method to define mock.On call
//   - appId string
//   - seriesName string
//   - value api.SeriesValue
func (_e *MockService_Expecter) AddSeriesValue(appId interface{}, seriesName interface{}, value interface{}) *MockService_AddSeriesValue_Call {
	return &MockService_AddSeriesValue_Call{Call: _e.mock.On("AddSeriesValue", appId, seriesName, value)}
}

func (_c *MockService_AddSeriesValue_Call) Run(run func(appId string, seriesName string, value api.SeriesValue)) *MockService_AddSeriesValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api.SeriesValue
		if args[2] != nil {
			arg2 = args[2].(api.SeriesValue)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_AddSeriesValue_Call) Return() *MockService_AddSeriesValue_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_AddSeriesValue_Call) RunAndReturn(run func(appId string, seriesName string, value api.SeriesValue)) *MockService_AddSeriesValue_Call {
	_c.Run(run)
	return _c
}

// AddStatusChangeTrigger provides a mock function for the type MockService
func (_mock *MockService) AddStatusChangeTrigger(appId string, trigger api.StatusChangeTrigger) api.StatusChangeTrigger {
	ret := _mock.Called(appId, trigger)

	if len(ret) == 0 {
		panic("no return value specified for AddStatusChangeTrigger")
	}

	var r0 api.StatusChangeTrigger
	if returnFunc, ok := ret.Get(0).(func(string, api.StatusChangeTrigger) api.StatusChangeTrigger); ok {
		r0 = returnFunc(appId, trigger)
	} else {
		r0 = ret.Get(0).(api.StatusChangeTrigger)
	}
	return r0
}

// MockService_AddStatusChangeTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddStatusChangeTrigger'
type MockService_AddStatusChangeTrigger_Call struct {
	*mock.Call
}

// AddStatusChangeTrigger is a helper method to define mock.On call
//   - appId string
//   - trigger api.StatusChangeTrigger
func (_e *MockService_Expecter) AddStatusChangeTrigger(appId interface{}, trigger interface{}) *MockService_AddStatusChangeTrigger_Call {
	return &MockService_AddStatusChangeTrigger_Call{Call: _e.mock.On("AddStatusChangeTrigger", appId, trigger)}
}

func (_c *MockService_AddStatusChangeTrigger_Call) Run(run func(appId string, trigger api.StatusChangeTrigger)) *MockService_AddStatusChangeTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 api.StatusChangeTrigger
		if args[1] != nil {
			arg1 = args[1].(api.StatusChangeTrigger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_AddStatusChangeTrigger_Call) Return(statusChangeTrigger api.StatusChangeTrigger) *MockService_AddStatusChangeTrigger_Call {
	_c.Call.Return(statusChangeTrigger)
	return _c
}

func (_c *MockService_AddStatusChangeTrigger_Call) RunAndReturn(run func(appId string, trigger api.StatusChangeTrigger) api.StatusChangeTrigger) *MockService_AddStatusChangeTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// Cached provides a mock function for the type MockService
func (_mock *MockService) Cached() service.Cached {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cached")
	}

	var r0 service.Cached
	if returnFunc, ok := ret.Get(0).(func() service.Cached); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.Cached)
		}
	}
	return r0
}

// MockService_Cached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cached'
type MockService_Cached_Call struct {
	*mock.Call
}

// Cached is a helper method to define mock.On call
func (_e *MockService_Expecter) Cached() *MockService_Cached_Call {
	return &MockService_Cached_Call{Call: _e.mock.On("Cached")}
}

func (_c *MockService_Cached_Call) Run(run func()) *MockService_Cached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Cached_Call) Return(cached service.Cached) *MockService_Cached_Call {
	_c.Call.Return(cached)
	return _c
}

func (_c *MockService_Cached_Call) RunAndReturn(run func() service.Cached) *MockService_Cached_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteApplication provides a mock function for the type MockService
func (_mock *MockService) DeleteApplication(id string) {
	_mock.Called(id)
	return
}

// MockService_DeleteApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApplication'
type MockService_DeleteApplication_Call struct {
	*mock.Call
}

// DeleteApplication is a helper method to define mock.On call
//   - id string
func (_e *MockService_Expecter) DeleteApplication(id interface{}) *MockService_DeleteApplication_Call {
	return &MockService_DeleteApplication_Call{Call: _e.mock.On("DeleteApplication", id)}
}

func (_c *MockService_DeleteApplication_Call) Run(run func(id string)) *MockService_DeleteApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteApplication_Call) Return() *MockService_DeleteApplication_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_DeleteApplication_Call) RunAndReturn(run func(id string)) *MockService_DeleteApplication_Call {
	_c.Run(run)
	return _c
}

// DeleteCronTrigger provides a mock function for the type MockService
func (_mock *MockService) DeleteCronTrigger(id int) {
	_mock.Called(id)
	return
}

// MockService_DeleteCronTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCronTrigger'
type MockService_DeleteCronTrigger_Call struct {
	*mock.Call
}

// DeleteCronTrigger is a helper method to define mock.On call
//   - id int
func (_e *MockService_Expecter) DeleteCronTrigger(id interface{}) *MockService_DeleteCronTrigger_Call {
	return &MockService_DeleteCronTrigger_Call{Call: _e.mock.On("DeleteCronTrigger", id)}
}

func (_c *MockService_DeleteCronTrigger_Call) Run(run func(id int)) *MockService_DeleteCronTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteCronTrigger_Call) Return() *MockService_DeleteCronTrigger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_DeleteCronTrigger_Call) RunAndReturn(run func(id int)) *MockService_DeleteCronTrigger_Call {
	_c.Run(run)
	return _c
}

// DeleteStatusChangeTrigger provides a mock function for the type MockService
func (_mock *MockService) DeleteStatusChangeTrigger(appId string) {
	_mock.Called(appId)
	return
}

// MockService_DeleteStatusChangeTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStatusChangeTrigger'
type MockService_DeleteStatusChangeTrigger_Call struct {
	*mock.Call
}

// DeleteStatusChangeTrigger is a helper method to define mock.On call
//   - appId string
func (_e *MockService_Expecter) DeleteStatusChangeTrigger(appId interface{}) *MockService_DeleteStatusChangeTrigger_Call {
	return &MockService_DeleteStatusChangeTrigger_Call{Call: _e.mock.On("DeleteStatusChangeTrigger", appId)}
}

func (_c *MockService_DeleteStatusChangeTrigger_Call) Run(run func(appId string)) *MockService_DeleteStatusChangeTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteStatusChangeTrigger_Call) Return() *MockService_DeleteStatusChangeTrigger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_DeleteStatusChangeTrigger_Call) RunAndReturn(run func(appId string)) *MockService_DeleteStatusChangeTrigger_Call {
	_c.Run(run)
	return _c
}

// GetApplication provides a mock function for the type MockService
func (_mock *MockService) GetApplication(id string) api.Application {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetApplication")
	}

	var r0 api.Application
	if returnFunc, ok := ret.Get(0).(func(string) api.Application); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(api.Application)
	}
	return r0
}

// MockService_GetApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplication'
type MockService_GetApplication_Call struct {
	*mock.Call
}

// GetApplication is a helper method to define mock.On call
//   - id string
func (_e *MockService_Expecter) GetApplication(id interface{}) *MockService_GetApplication_Call {
	return &MockService_GetApplication_Call{Call: _e.mock.On("GetApplication", id)}
}

func (_c *MockService_GetApplication_Call) Run(run func(id string)) *MockService_GetApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetApplication_Call) Return(application api.Application) *MockService_GetApplication_Call {
	_c.Call.Return(application)
	return _c
}

func (_c *MockService_GetApplication_Call) RunAndReturn(run func(id string) api.Application) *MockService_GetApplication_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfiguration provides a mock function for the type MockService
func (_mock *MockService) GetConfiguration(appId string) api.Configuration {
	ret := _mock.Called(appId)

	if len(ret) == 0 {
		panic("no return value specified for GetConfiguration")
	}

	var r0 api.Configuration
	if returnFunc, ok := ret.Get(0).(func(string) api.Configuration); ok {
		r0 = returnFunc(appId)
	} else {
		r0 = ret.Get(0).(api.Configuration)
	}
	return r0
}

// MockService_GetConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfiguration'
type MockService_GetConfiguration_Call struct {
	*mock.Call
}

// GetConfiguration is a helper method to define mock.On call
//   - appId string
func (_e *MockService_Expecter) GetConfiguration(appId interface{}) *MockService_GetConfiguration_Call {
	return &MockService_GetConfiguration_Call{Call: _e.mock.On("GetConfiguration", appId)}
}

func (_c *MockService_GetConfiguration_Call) Run(run func(appId string)) *MockService_GetConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetConfiguration_Call) Return(configuration api.Configuration) *MockService_GetConfiguration_Call {
	_c.Call.Return(configuration)
	return _c
}

func (_c *MockService_GetConfiguration_Call) RunAndReturn(run func(appId string) api.Configuration) *MockService_GetConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GetCronTrigger provides a mock function for the type MockService
func (_mock *MockService) GetCronTrigger(id int) *api.CronTrigger {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCronTrigger")
	}

	var r0 *api.CronTrigger
	if returnFunc, ok := ret.Get(0).(func(int) *api.CronTrigger); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.CronTrigger)
		}
	}
	return r0
}

// MockService_GetCronTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCronTrigger'
type MockService_GetCronTrigger_Call struct {
	*mock.Call
}

// GetCronTrigger is a helper method to define mock.On call
//   - id int
func (_e *MockService_Expecter) GetCronTrigger(id interface{}) *MockService_GetCronTrigger_Call {
	return &MockService_GetCronTrigger_Call{Call: _e.mock.On("GetCronTrigger", id)}
}

func (_c *MockService_GetCronTrigger_Call) Run(run func(id int)) *MockService_GetCronTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetCronTrigger_Call) Return(cronTrigger *api.CronTrigger) *MockService_GetCronTrigger_Call {
	_c.Call.Return(cronTrigger)
	return _c
}

func (_c *MockService_GetCronTrigger_Call) RunAndReturn(run func(id int) *api.CronTrigger) *MockService_GetCronTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeries provides a mock function for the type MockService
func (_mock *MockService) GetSeries(appId string, seriesName string) api.Series {
	ret := _mock.Called(appId, seriesName)

	if len(ret) == 0 {
		panic("no return value specified for GetSeries")
	}

	var r0 api.Series
	if returnFunc, ok := ret.Get(0).(func(string, string) api.Series); ok {
		r0 = returnFunc(appId, seriesName)
	} else {
		r0 = ret.Get(0).(api.Series)
	}
	return r0
}

// MockService_GetSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeries'
type MockService_GetSeries_Call struct {
	*mock.Call
}

// GetSeries is a helper method to define mock.On call
//   - appId string
//   - seriesName string
func (_e *MockService_Expecter) GetSeries(appId interface{}, seriesName interface{}) *MockService_GetSeries_Call {
	return &MockService_GetSeries_Call{Call: _e.mock.On("GetSeries", appId, seriesName)}
}

func (_c *MockService_GetSeries_Call) Run(run func(appId string, seriesName string)) *MockService_GetSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetSeries_Call) Return(series api.Series) *MockService_GetSeries_Call {
	_c.Call.Return(series)
	return _c
}

func (_c *MockService_GetSeries_Call) RunAndReturn(run func(appId string, seriesName string) api.Series) *MockService_GetSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusChangeTrigger provides a mock function for the type MockService
func (_mock *MockService) GetStatusChangeTrigger(appId string) *api.StatusChangeTrigger {
	ret := _mock.Called(appId)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusChangeTrigger")
	}

	var r0 *api.StatusChangeTrigger
	if returnFunc, ok := ret.Get(0).(func(string) *api.StatusChangeTrigger); ok {
		r0 = returnFunc(appId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.StatusChangeTrigger)
		}
	}
	return r0
}

// MockService_GetStatusChangeTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusChangeTrigger'
type MockService_GetStatusChangeTrigger_Call struct {
	*mock.Call
}

// GetStatusChangeTrigger is a helper method to define mock.On call
//   - appId string
func (_e *MockService_Expecter) GetStatusChangeTrigger(appId interface{}) *MockService_GetStatusChangeTrigger_Call {
	return &MockService_GetStatusChangeTrigger_Call{Call: _e.mock.On("GetStatusChangeTrigger", appId)}
}

func (_c *MockService_GetStatusChangeTrigger_Call) Run(run func(appId string)) *MockService_GetStatusChangeTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetStatusChangeTrigger_Call) Return(statusChangeTrigger *api.StatusChangeTrigger) *MockService_GetStatusChangeTrigger_Call {
	_c.Call.Return(statusChangeTrigger)
	return _c
}

func (_c *MockService_GetStatusChangeTrigger_Call) RunAndReturn(run func(appId string) *api.StatusChangeTrigger) *MockService_GetStatusChangeTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// InitSeries provides a mock function for the type MockService
func (_mock *MockService) InitSeries(appId string, series api.Series) {
	_mock.Called(appId, series)
	return
}

// MockService_InitSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitSeries'
type MockService_InitSeries_Call struct {
	*mock.Call
}

// InitSeries is a helper method to define mock.On call
//   - appId string
//   - series api.Series
func (_e *MockService_Expecter) InitSeries(appId interface{}, series interface{}) *MockService_InitSeries_Call {
	return &MockService_InitSeries_Call{Call: _e.mock.On("InitSeries", appId, series)}
}

func (_c *MockService_InitSeries_Call) Run(run func(appId string, series api.Series)) *MockService_InitSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 api.Series
		if args[1] != nil {
			arg1 = args[1].(api.Series)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_InitSeries_Call) Return() *MockService_InitSeries_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_InitSeries_Call) RunAndReturn(run func(appId string, series api.Series)) *MockService_InitSeries_Call {
	_c.Run(run)
	return _c
}

// IsAllowed provides a mock function for the type MockService
func (_mock *MockService) IsAllowed(appId string, apiKey string) bool {
	ret := _mock.Called(appId, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(appId, apiKey)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type MockService_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - appId string
//   - apiKey string
func (_e *MockService_Expecter) IsAllowed(appId interface{}, apiKey interface{}) *MockService_IsAllowed_Call {
	return &MockService_IsAllowed_Call{Call: _e.mock.On("IsAllowed", appId, apiKey)}
}

func (_c *MockService_IsAllowed_Call) Run(run func(appId string, apiKey string)) *MockService_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_IsAllowed_Call) Return(b bool) *MockService_IsAllowed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_IsAllowed_Call) RunAndReturn(run func(appId string, apiKey string) bool) *MockService_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// IsOnline provides a mock function for the type MockService
func (_mock *MockService) IsOnline(appId string) bool {
	ret := _mock.Called(appId)

	if len(ret) == 0 {
		panic("no return value specified for IsOnline")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(appId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_IsOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOnline'
type MockService_IsOnline_Call struct {
	*mock.Call
}

// IsOnline is a helper method to define mock.On call
//   - appId string
func (_e *MockService_Expecter) IsOnline(appId interface{}) *MockService_IsOnline_Call {
	return &MockService_IsOnline_Call{Call: _e.mock.On("IsOnline", appId)}
}

func (_c *MockService_IsOnline_Call) Run(run func(appId string)) *MockService_IsOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_IsOnline_Call) Return(b bool) *MockService_IsOnline_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_IsOnline_Call) RunAndReturn(run func(appId string) bool) *MockService_IsOnline_Call {
	_c.Call.Return(run)
	return _c
}

// IsValid provides a mock function for the type MockService
func (_mock *MockService) IsValid(request api.CronValidationRequest) bool {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for IsValid")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.CronValidationRequest) bool); ok {
		r0 = returnFunc(request)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_IsValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValid'
type MockService_IsValid_Call struct {
	*mock.Call
}

// IsValid is a helper method to define mock.On call
//   - request api.CronValidationRequest
func (_e *MockService_Expecter) IsValid(request interface{}) *MockService_IsValid_Call {
	return &MockService_IsValid_Call{Call: _e.mock.On("IsValid", request)}
}

func (_c *MockService_IsValid_Call) Run(run func(request api.CronValidationRequest)) *MockService_IsValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.CronValidationRequest
		if args[0] != nil {
			arg0 = args[0].(api.CronValidationRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_IsValid_Call) Return(b bool) *MockService_IsValid_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_IsValid_Call) RunAndReturn(run func(request api.CronValidationRequest) bool) *MockService_IsValid_Call {
	_c.Call.Return(run)
	return _c
}

// Joined provides a mock function for the type MockService
func (_mock *MockService) Joined(appId string) {
	_mock.Called(appId)
	return
}

// MockService_Joined_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Joined'
type MockService_Joined_Call struct {
	*mock.Call
}

// Joined is a helper method to define mock.On call
//   - appId string
func (_e *MockService_Expecter) Joined(appId interface{}) *MockService_Joined_Call {
	return &MockService_Joined_Call{Call: _e.mock.On("Joined", appId)}
}

func (_c *MockService_Joined_Call) Run(run func(appId string)) *MockService_Joined_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Joined_Call) Return() *MockService_Joined_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Joined_Call) RunAndReturn(run func(appId string)) *MockService_Joined_Call {
	_c.Run(run)
	return _c
}

// Left provides a mock function for the type MockService
func (_mock *MockService) Left(appId string) {
	_mock.Called(appId)
	return
}

// MockService_Left_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Left'
type MockService_Left_Call struct {
	*mock.Call
}

// Left is a helper method to define mock.On call
//   - appId string
func (_e *MockService_Expecter) Left(appId interface{}) *MockService_Left_Call {
	return &MockService_Left_Call{Call: _e.mock.On("Left", appId)}
}

func (_c *MockService_Left_Call) Run(run func(appId string)) *MockService_Left_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Left_Call) Return() *MockService_Left_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Left_Call) RunAndReturn(run func(appId string)) *MockService_Left_Call {
	_c.Run(run)
	return _c
}

// ListApplications provides a mock function for the type MockService
func (_mock *MockService) ListApplications() []api.Application {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListApplications")
	}

	var r0 []api.Application
	if returnFunc, ok := ret.Get(0).(func() []api.Application); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.Application)
		}
	}
	return r0
}

// MockService_ListApplications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApplications'
type MockService_ListApplications_Call struct {
	*mock.Call
}

// ListApplications is a helper method to define mock.On call
func (_e *MockService_Expecter) ListApplications() *MockService_ListApplications_Call {
	return &MockService_ListApplications_Call{Call: _e.mock.On("ListApplications")}
}

func (_c *MockService_ListApplications_Call) Run(run func()) *MockService_ListApplications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_ListApplications_Call) Return(applications []api.Application) *MockService_ListApplications_Call {
	_c.Call.Return(applications)
	return _c
}

func (_c *MockService_ListApplications_Call) RunAndReturn(run func() []api.Application) *MockService_ListApplications_Call {
	_c.Call.Return(run)
	return _c
}

// ListCronTriggers provides a mock function for the type MockService
func (_mock *MockService) ListCronTriggers() []api.CronTrigger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListCronTriggers")
	}

	var r0 []api.CronTrigger
	if returnFunc, ok := ret.Get(0).(func() []api.CronTrigger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.CronTrigger)
		}
	}
	return r0
}

// MockService_ListCronTriggers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCronTriggers'
type MockService_ListCronTriggers_Call struct {
	*mock.Call
}

// ListCronTriggers is a helper method to define mock.On call
func (_e *MockService_Expecter) ListCronTriggers() *MockService_ListCronTriggers_Call {
	return &MockService_ListCronTriggers_Call{Call: _e.mock.On("ListCronTriggers")}
}

func (_c *MockService_ListCronTriggers_Call) Run(run func()) *MockService_ListCronTriggers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_ListCronTriggers_Call) Return(cronTriggers []api.CronTrigger) *MockService_ListCronTriggers_Call {
	_c.Call.Return(cronTriggers)
	return _c
}

func (_c *MockService_ListCronTriggers_Call) RunAndReturn(run func() []api.CronTrigger) *MockService_ListCronTriggers_Call {
	_c.Call.Return(run)
	return _c
}

// ListSeries provides a mock function for the type MockService
func (_mock *MockService) ListSeries(appId string) []api.Series {
	ret := _mock.Called(appId)

	if len(ret) == 0 {
		panic("no return value specified for ListSeries")
	}

	var r0 []api.Series
	if returnFunc, ok := ret.Get(0).(func(string) []api.Series); ok {
		r0 = returnFunc(appId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.Series)
		}
	}
	return r0
}

// MockService_ListSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSeries'
type MockService_ListSeries_Call struct {
	*mock.Call
}

// ListSeries is a helper method to define mock.On call
//   - appId string
func (_e *MockService_Expecter) ListSeries(appId interface{}) *MockService_ListSeries_Call {
	return &MockService_ListSeries_Call{Call: _e.mock.On("ListSeries", appId)}
}

func (_c *MockService_ListSeries_Call) Run(run func(appId string)) *MockService_ListSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListSeries_Call) Return(seriess []api.Series) *MockService_ListSeries_Call {
	_c.Call.Return(seriess)
	return _c
}

func (_c *MockService_ListSeries_Call) RunAndReturn(run func(appId string) []api.Series) *MockService_ListSeries_Call {
	_c.Call.Return(run)
	return _c
}

// ListSeriesValues provides a mock function for the type MockService
func (_mock *MockService) ListSeriesValues(appId string, seriesName string, sort service.Sort, pagination service.Pagination) api.SeriesValues {
	ret := _mock.Called(appId, seriesName, sort, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListSeriesValues")
	}

	var r0 api.SeriesValues
	if returnFunc, ok := ret.Get(0).(func(string, string, service.Sort, service.Pagination) api.SeriesValues); ok {
		r0 = returnFunc(appId, seriesName, sort, pagination)
	} else {
		r0 = ret.Get(0).(api.SeriesValues)
	}
	return r0
}

// MockService_ListSeriesValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSeriesValues'
type MockService_ListSeriesValues_Call struct {
	*mock.Call
}

// ListSeriesValues is a helper method to define mock.On call
//   - appId string
//   - seriesName string
//   - sort service.Sort
//   - pagination service.Pagination
func (_e *MockService_Expecter) ListSeriesValues(appId interface{}, seriesName interface{}, sort interface{}, pagination interface{}) *MockService_ListSeriesValues_Call {
	return &MockService_ListSeriesValues_Call{Call: _e.mock.On("ListSeriesValues", appId, seriesName, sort, pagination)}
}

func (_c *MockService_ListSeriesValues_Call) Run(run func(appId string, seriesName string, sort service.Sort, pagination service.Pagination)) *MockService_ListSeriesValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 service.Sort
		if args[2] != nil {
			arg2 = args[2].(service.Sort)
		}
		var arg3 service.Pagination
		if args[3] != nil {
			arg3 = args[3].(service.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_ListSeriesValues_Call) Return(seriesValues api.SeriesValues) *MockService_ListSeriesValues_Call {
	_c.Call.Return(seriesValues)
	return _c
}

func (_c *MockService_ListSeriesValues_Call) RunAndReturn(run func(appId string, seriesName string, sort service.Sort, pagination service.Pagination) api.SeriesValues) *MockService_ListSeriesValues_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockService
func (_mock *MockService) Login(login string, password string) bool {
	ret := _mock.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(login, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - login string
//   - password string
func (_e *MockService_Expecter) Login(login interface{}, password interface{}) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", login, password)}
}

func (_c *MockService_Login_Call) Run(run func(login string, password string)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Login_Call) Return(b bool) *MockService_Login_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(login string, password string) bool) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewPagination provides a mock function for the type MockService
func (_mock *MockService) NewPagination(size int, defaultSize int, page int) service.Pagination {
	ret := _mock.Called(size, defaultSize, page)

	if len(ret) == 0 {
		panic("no return value specified for NewPagination")
	}

	var r0 service.Pagination
	if returnFunc, ok := ret.Get(0).(func(int, int, int) service.Pagination); ok {
		r0 = returnFunc(size, defaultSize, page)
	} else {
		r0 = ret.Get(0).(service.Pagination)
	}
	return r0
}

// MockService_NewPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewPagination'
type MockService_NewPagination_Call struct {
	*mock.Call
}

// NewPagination is a helper method to define mock.On call
//   - size int
//   - defaultSize int
//   - page int
func (_e *MockService_Expecter) NewPagination(size interface{}, defaultSize interface{}, page interface{}) *MockService_NewPagination_Call {
	return &MockService_NewPagination_Call{Call: _e.mock.On("NewPagination", size, defaultSize, page)}
}

func (_c *MockService_NewPagination_Call) Run(run func(size int, defaultSize int, page int)) *MockService_NewPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_NewPagination_Call) Return(pagination service.Pagination) *MockService_NewPagination_Call {
	_c.Call.Return(pagination)
	return _c
}

func (_c *MockService_NewPagination_Call) RunAndReturn(run func(size int, defaultSize int, page int) service.Pagination) *MockService_NewPagination_Call {
	_c.Call.Return(run)
	return _c
}

// NewSort provides a mock function for the type MockService
func (_mock *MockService) NewSort(sort string, defaultSort string, dir string) service.Sort {
	ret := _mock.Called(sort, defaultSort, dir)

	if len(ret) == 0 {
		panic("no return value specified for NewSort")
	}

	var r0 service.Sort
	if returnFunc, ok := ret.Get(0).(func(string, string, string) service.Sort); ok {
		r0 = returnFunc(sort, defaultSort, dir)
	} else {
		r0 = ret.Get(0).(service.Sort)
	}
	return r0
}

// MockService_NewSort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSort'
type MockService_NewSort_Call struct {
	*mock.Call
}

// NewSort is a helper method to define mock.On call
//   - sort string
//   - defaultSort string
//   - dir string
func (_e *MockService_Expecter) NewSort(sort interface{}, defaultSort interface{}, dir interface{}) *MockService_NewSort_Call {
	return &MockService_NewSort_Call{Call: _e.mock.On("NewSort", sort, defaultSort, dir)}
}

func (_c *MockService_NewSort_Call) Run(run func(sort string, defaultSort string, dir string)) *MockService_NewSort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_NewSort_Call) Return(sort1 service.Sort) *MockService_NewSort_Call {
	_c.Call.Return(sort1)
	return _c
}

func (_c *MockService_NewSort_Call) RunAndReturn(run func(sort string, defaultSort string, dir string) service.Sort) *MockService_NewSort_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateApplication provides a mock function for the type MockService
func (_mock *MockService) UpdateApplication(application api.Application) api.Application {
	ret := _mock.Called(application)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApplication")
	}

	var r0 api.Application
	if returnFunc, ok := ret.Get(0).(func(api.Application) api.Application); ok {
		r0 = returnFunc(application)
	} else {
		r0 = ret.Get(0).(api.Application)
	}
	return r0
}

// MockService_UpdateApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateApplication'
type MockService_UpdateApplication_Call struct {
	*mock.Call
}

// UpdateApplication is a helper method to define mock.On call
//   - application api.Application
func (_e *MockService_Expecter) UpdateApplication(application interface{}) *MockService_UpdateApplication_Call {
	return &MockService_UpdateApplication_Call{Call: _e.mock.On("UpdateApplication", application)}
}

func (_c *MockService_UpdateApplication_Call) Run(run func(application api.Application)) *MockService_UpdateApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.Application
		if args[0] != nil {
			arg0 = args[0].(api.Application)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_UpdateApplication_Call) Return(application1 api.Application) *MockService_UpdateApplication_Call {
	_c.Call.Return(application1)
	return _c
}

func (_c *MockService_UpdateApplication_Call) RunAndReturn(run func(application api.Application) api.Application) *MockService_UpdateApplication_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCronTrigger provides a mock function for the type MockService
func (_mock *MockService) UpdateCronTrigger(trigger api.CronTrigger) api.CronTrigger {
	ret := _mock.Called(trigger)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCronTrigger")
	}

	var r0 api.CronTrigger
	if returnFunc, ok := ret.Get(0).(func(api.CronTrigger) api.CronTrigger); ok {
		r0 = returnFunc(trigger)
	} else {
		r0 = ret.Get(0).(api.CronTrigger)
	}
	return r0
}

// MockService_UpdateCronTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCronTrigger'
type MockService_UpdateCronTrigger_Call struct {
	*mock.Call
}

// UpdateCronTrigger is a helper method to define mock.On call
//   - trigger api.CronTrigger
func (_e *MockService_Expecter) UpdateCronTrigger(trigger interface{}) *MockService_UpdateCronTrigger_Call {
	return &MockService_UpdateCronTrigger_Call{Call: _e.mock.On("UpdateCronTrigger", trigger)}
}

func (_c *MockService_UpdateCronTrigger_Call) Run(run func(trigger api.CronTrigger)) *MockService_UpdateCronTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.CronTrigger
		if args[0] != nil {
			arg0 = args[0].(api.CronTrigger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_UpdateCronTrigger_Call) Return(cronTrigger api.CronTrigger) *MockService_UpdateCronTrigger_Call {
	_c.Call.Return(cronTrigger)
	return _c
}

func (_c *MockService_UpdateCronTrigger_Call) RunAndReturn(run func(trigger api.CronTrigger) api.CronTrigger) *MockService_UpdateCronTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusChangeTrigger provides a mock function for the type MockService
func (_mock *MockService) UpdateStatusChangeTrigger(appId string, trigger api.StatusChangeTrigger) api.StatusChangeTrigger {
	ret := _mock.Called(appId, trigger)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusChangeTrigger")
	}

	var r0 api.StatusChangeTrigger
	if returnFunc, ok := ret.Get(0).(func(string, api.StatusChangeTrigger) api.StatusChangeTrigger); ok {
		r0 = returnFunc(appId, trigger)
	} else {
		r0 = ret.Get(0).(api.StatusChangeTrigger)
	}
	return r0
}

// MockService_UpdateStatusChangeTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusChangeTrigger'
type MockService_UpdateStatusChangeTrigger_Call struct {
	*mock.Call
}

// UpdateStatusChangeTrigger is a helper method to define mock.On call
//   - appId string
//   - trigger api.StatusChangeTrigger
func (_e *MockService_Expecter) UpdateStatusChangeTrigger(appId interface{}, trigger interface{}) *MockService_UpdateStatusChangeTrigger_Call {
	return &MockService_UpdateStatusChangeTrigger_Call{Call: _e.mock.On("UpdateStatusChangeTrigger", appId, trigger)}
}

func (_c *MockService_UpdateStatusChangeTrigger_Call) Run(run func(appId string, trigger api.StatusChangeTrigger)) *MockService_UpdateStatusChangeTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 api.StatusChangeTrigger
		if args[1] != nil {
			arg1 = args[1].(api.StatusChangeTrigger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_UpdateStatusChangeTrigger_Call) Return(statusChangeTrigger api.StatusChangeTrigger) *MockService_UpdateStatusChangeTrigger_Call {
	_c.Call.Return(statusChangeTrigger)
	return _c
}

func (_c *MockService_UpdateStatusChangeTrigger_Call) RunAndReturn(run func(appId string, trigger api.StatusChangeTrigger) api.StatusChangeTrigger) *MockService_UpdateStatusChangeTrigger_Call {
	_c.Call.Return(run)
	return _c
}
